export const ActionType = {
  GET_MOVIES: "GET_MOVIES",
  GET_RATED_MOVIES: "GET_RATED_MOVIES",
  GET_TREDING_TV: " GET_TREDING_TV",
  GET_TVSERIES: " GET_TVSERIES",
  GET_DETAIL: "GET_DETAIL",
  SEARCH_MOVIES: "SEARCH_MOVIES",
};
